---
title: "Semana2-Hipotesis"
format: html
editor: visual
---

```{r}
x <- c("ggplot2", "tidyr", "tidyverse", "dplyr", "patchwork")
for (i in x){library(i, character.only = TRUE)}

rm(x)
```

### Testear hipotesis

### Let's create a random data set

```{r}
set.seed(28)
datos_n <- rnorm(100, mean = 115, sd = 24 )
data <- data.frame(1:100)
data$datos <- datos_n
data <- data %>% select(-X1.100)
rm(datos_n)

theme <- theme_minimal(base_size = 11) + theme(
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.4),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5)
      )


p1 <- ggplot(data, aes(x=datos)) +  geom_histogram(aes(y = ..density..), bins = 30, fill = "lightblue", color = "black") + geom_density(color = "blue") + geom_vline(xintercept = 115, color="red") + geom_vline(xintercept = 115 + 24, linetype = "dashed", color = "darkgreen", size = 1) + geom_vline(xintercept = 115 - 24, linetype = "dashed", color = "darkgreen", size = 1) + labs(x = "Peso de los bebes (lb)") + theme 

```

$$ H_{A} : \bar{\mu}_{p} < \bar{X}$$ $$ H_{0} : \bar{\mu}_{p} = \bar{X} $$

### Standar scores

```{r}
#### Z-score and T-score
data$zcore <- (data$datos - 115)/24 
data$tscore <- (data$zcore*10 + 50)


p2 <- ggplot(data, aes(x=zcore)) + geom_histogram(aes(y = ..density..), bins = 30, fill = "lightblue", color = "black") + geom_density(color = "blue")  + geom_vline(xintercept = 0, color="red") +  theme 

p3 <- ggplot(data, aes(x=tscore)) + geom_histogram(aes(y = ..density..), bins = 30, fill = "lightblue", color = "black") + geom_density(color = "blue") + geom_vline(xintercept = 50, color="red") +  theme 

(p1|p2|p3)
```

Our \$95 % \$ confidence interval is delimited by 1.96.
